# Generated by Django 3.2.9 on 2021-12-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_artical'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artical',
            new_name='Article',
        ),
    ]
